export let rankNames =  [
    "Earth I ",
    "Earth II",
    "Earth III ",
    "Grass I ",
    "Grass II",
    "Grass III ",
    "Grass IIII",
    "Water I ",
    "Water II",
    "Water III ",
    "Fire I",
    "Fire II ",
    "Fire III",
    "Gold I",
    "Gold II ",
    "Gold III",
    "Platinum I",
    "Platinum II ",
    "Platinum III",
    "Elite ",
    "Master",
    "Grandmaster"
]